    services:
  - type: web
    name: jua-smart-web # Your web service name
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn --worker-tmp-dir /dev/shm juasmart.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase: # Reference your database here, if you have one
          name: YourDatabaseName # Replace with your actual database name on Render
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
    # staticFiles: <--- THIS BLOCK SHOULD BE GONE
    #   - path: ./staticfiles
    #     url: /static/
